#server
server:
  port: 80
  address: localhost
#前端项目地址
web:
  path: http://localhost:90


spring:
  #datasource
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.173.242:3306/campus?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 12345
    type: com.alibaba.druid.pool.DruidDataSource
  #抛出没有处理器的异常
  mvc:
    throw-exception-if-no-handler-found: true
  #redis
  redis:
    port: 6379
    host: 118.31.173.242
    database: 0
    password: 13340116773
#mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    #自动驼峰映射
    map-underscore-to-camel-case: true

# rocketMQ
#rocketmq:
#  name-server: 118.31.173.242:9876
#  producer:
#    group: seckill_producer
